/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
            colors: {
              "inverse-on-surface": "#303032",
              "error": "#ffb4ab",
              "surface-container-low": "#1b1c1d",
              "primary-container": "#5e6ad2",
              "on-primary": "#121f8b",
              "tertiary-fixed": "#cce5ff",
              "on-surface-variant": "#c6c5d5",
              "on-primary-fixed-variant": "#2e3aa2",
              "surface": "#121315",
              "inverse-primary": "#4854bb",
              "on-error": "#690005",
              "surface-bright": "#38393a",
              "secondary-fixed": "#dbe2fb",
              "primary": "#bdc2ff",
              "on-primary-fixed": "#000965",
              "secondary-container": "#41495d",
              "outline-variant": "#454652",
              "surface-container-high": "#292a2b",
              "primary-fixed-dim": "#bdc2ff",
              "primary-fixed": "#dfe0ff",
              "on-tertiary-container": "#fbfbff",
              "surface-variant": "#343536",
              "inverse-surface": "#e3e2e3",
              "secondary-fixed-dim": "#bfc6de",
              "outline": "#908f9e",
              "secondary": "#bfc6de",
              "surface-container-lowest": "#0d0e0f",
              "on-tertiary-fixed": "#001d31",
              "surface-tint": "#bdc2ff",
              "on-surface": "#e3e2e3",
              "error-container": "#93000a",
              "on-primary-container": "#fdfaff",
              "on-secondary": "#293043",
              "on-background": "#e3e2e3",
              "on-error-container": "#ffdad6",
              "on-tertiary": "#003351",
              "tertiary": "#92ccff",
              "tertiary-fixed-dim": "#92ccff",
              "tertiary-container": "#007ab8",
              "on-secondary-fixed": "#141b2d",
              "surface-container-highest": "#343536",
              "on-secondary-fixed-variant": "#3f465a",
              "surface-container": "#1f2021",
              "background": "#121315",
              "on-secondary-container": "#b1b8d0",
              "on-tertiary-fixed-variant": "#004b73",
              "surface-dim": "#121315"
            },
            fontFamily: {
              "headline": ["Inter"],
              "body": ["Inter"],
              "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
          },
  },
  plugins: [],
};
